### ISSUE TITLE
How to exclude node_modules?

### ISSUE THREAD

**Issue by alexhribsek** [sds/scss-lint#980]
This is my YAML (part of it):

```
scss_files: '**/*.scss'

exclude: 'node_modules/**'
```

`node_modules` is not being excluded. What am I doing wrong?

**Comment by sds** [comment]
How are you invoking `scss-lint`? Via some other program? Are you passing files as arguments in a way where they could be referenced via a symlink that isn't excluded? 

Will need more information to help understand this issue. Thanks!
