### ISSUE TITLE
scss-lint not compatible with IntelliJ IDEA Educational Edition 2019.3 x64

### ISSUE THREAD

**Issue by Sharlikran** [sds/scss-lint#983]
https://github.com/idok/scss-lint-plugin/issues/67

Where is the support thread for this I can't get it to work. I gave a detailed list of the docs, gave screen shots, installed nodejs, and everything I could find on any instructional page. Nothing works. When I open Pycharm it doesn't use the scss-lint feature and I can't configure it because there are no config files, no scss-lint.exe nothing. What do I do?

**Comment by ianadavies** [comment]
I am having this exact same problem with Rider 2019.3

**Comment by sds** [comment]
This project is not responsible for any third-party plugins that use it. Please keep your requests to the plugin.
