### ISSUE TITLE
Support --fix like eslint --fix to autofix whitespace related formatting lint issues

### ISSUE THREAD

**Issue by nojvek** [sds/scss-lint#984]

**Comment by sds** [comment]
As discussed in https://github.com/sds/scss-lint/issues/282#issuecomment-61310649, this is not possible. The Sass Ruby implementation simply does not allow us to modify the parse tree while preserving other elements of whitespace.

If you want to focus solely on updating whitespace, recommend you look into writing something with `sed` or similar.
