### ISSUE TITLE
sass-lint is unmaintained

### ISSUE THREAD

**Issue by ybiquitous** [sds/scss-lint#985]
Hi there,

The SCSS-Lint's current README [describes sass-lint](https://github.com/sds/scss-lint/blob/8db988731d3cecc4b3c9c63755b364a98858eca9/README.md#notice-consider-other-tools-before-adopting-scss-lint) as an alternative:

> Two alternatives worthy of consideration are stylelint and sass-lint, with sass-lint having closer feature parity to SCSS-lint.

However, sass-lint seems currently unmaintained. (see the sass-lint's [README](https://github.com/sasstools/sass-lint#readme))

So I'm concerned that the description for sass-lint can make users confused (like me). 😓 
I think the description should be removed from the README, but what do you think?

Thanks.

**Comment by lencioni** [comment]
Thanks for bringing this up! I agree it should be removed. Want to submit a PR?

**Comment by ybiquitous** [comment]
Yes, I'll do it. 👍
