### ISSUE TITLE
Request: add scroll-margin property to default whitelist

### ISSUE THREAD

**Issue by nali** [sds/scss-lint#987]
The [`scroll-margin` property](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin)  has wide support and is in a stable Candidate Recommendation stage: it would be great to add it to the default whitelist.

Happy to open a PR. :)

**Comment by sds** [comment]
Happy to merge a PR, Nali!

**Comment by nali** [comment]
PR #988 now merged. 🥳
